resources:
- name: cache-repo
  type: git
  source:
    uri: git@github.com:nattsw/concourse-cache.git
    branch: master
    private_key: ((private-key))

- name: cache-release
  type: github-release
  source:
    owner: nattsw
    repository: concourse-cache
    access_token: ((access-token))

- name: cache-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((concourse-email))
    password: ((concourse-password))
    organization: tomtom
    space: development
    skip_cert_check: false

jobs:
- name: release-build
  serial: true
  plan:
  - get: cache-repo
    trigger: true
  - task: build-jar
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: '8-jdk'
      inputs:
        - name: cache-repo
      outputs:
        - name: cache-repo-with-build
      run:
        path: sh
        args:
        - -exc
        - |
          git clone cache-repo cache-repo-with-build
          cd cache-repo-with-build
          export GRADLE_USER_HOME="$(pwd)/.gradle"
          ./gradlew clean bootJar
          date +'%s' > ci/release-info
      caches:
        - path: cache-repo-with-build/.gradle/
  - put: cache-release
    params:
      name: cache-repo-with-build/ci/release-info
      tag: cache-repo-with-build/ci/release-info
      globs:
      - cache-repo-with-build/build/libs/demo-*.jar
      - cache-repo-with-build/ci/manifest.yml

- name: deploy-build
  serial: true
  plan:
  - get: cache-release
    passed: [release-build]
    trigger: true
  - put: cache-cf
    params:
      manifest: cache-release/manifest.yml
